server:
    port: 8082
spring:
    application:
        name: Pgcrypto
    datasource:
        url: jdbc:postgresql://${SERVER_IP:localhost}:${POSTGRESQL_PORT:5432}/${POSTGRESQL_DB:pgcrypto}?currentSchema=${POSTGRESQL_SCHEMA:public}
        username: ${POSTGRESQL_USER:postgres}
        password: ${POSTGRESQL_PASSWORD:senocak}
    jpa:
        properties:
            hibernate:
                dialect: org.hibernate.dialect.PostgreSQLDialect
        hibernate:
            ddl-auto: create-drop
        show-sql: false
logging:
    level:
        org:
            hibernate:
                SQL: error
            springframework: info
